### ISSUE TITLE
Unexpected translation 

### ISSUE THREAD

**Issue by michael-emmi** [SRI-CSL/solidity#50]
solc-verify somehow parses and translates the `=>` operator in an illegal position, and generates an expression with only the left-hand side!
```
$ cat Test.sol && solc-verify.py Test.sol --output . ; grep "=>" Test.sol.bpl 
pragma solidity ^0.5.0;

contract Test {
    /// @notice postcondition x > 0 => y == 42
    /// @notice postcondition !(x > 0) || y == 42
    function foo(int x) public pure returns (int y) {
        return x > 0 ? 42 : 0;
    }
}
Test::foo: ERROR
 - Test.sol:6:5: Postcondition 'x > 0 => y == 42' might not hold at end of function.
Test::[implicit_constructor]: OK
Errors were found by the verifier.
	ensures {:sourceloc "Test.sol", 6, 5} {:message "Postcondition 'x > 0 = y == 42' might not hold at end of function."} (x#3 > 0);
```
Not clear what should be done here, but perhaps a warning or error would be good.

**Comment by hajduakos** [comment]
`=>` is not a valid operator in Solidity (there is no implication operator). Since 14a1240 we report an informative error message:
```
Annotation:1:7: solc-verify error: Expected end of expression but got '=>'
x > 0 => y == 42
      ^^
```

The problem was that we were reusing the expression parsing method from the compiler, which just looks for the tokens that it is actually expecting and ignores the rest. As far as I've seen in the rest of the parser, it is the responsibility of the parent statement to check if its inner expression was properly fully parsed. Now I added this check to our reused parser module as well.
